### ISSUE TITLE
[Bug Report] Minor/insubstantial issues with FUCTool v1.0.1(nothing major)

### ISSUE THREAD

**Issue by Abbanon** [FUComplete/FUCTool#1]
The FUCTool window can be horizontally stretched by a tiny amount - it only impacts the right side edge:
![comparison-01](https://user-images.githubusercontent.com/37251822/222073676-189659df-53de-4b20-acf9-25d7f93f67d4.png)

The bullet points for the HH Tweaks config should have proper vertical alignment:
![bulletbefore](https://user-images.githubusercontent.com/37251822/222074343-92d5670b-0825-4e8d-9b8e-12eea49e7996.png)
![bulletafter](https://user-images.githubusercontent.com/37251822/222074347-5ec491d6-de5f-4fcd-858e-6015fb996898.png)

**Comment by Hairo** [comment]
This will be fixed in the next release.
