### ISSUE TITLE
Configuration options not activating

### ISSUE THREAD

**Issue by imeasyplease** [FUComplete/FUCTool#3]
As the title says, none of my options I select in the FUC tool are activating.

**Comment by imeasyplease** [comment]
The config file is existant and the tool has it selected, despite this none of the config works in-game

**Comment by Hairo** [comment]
Is your config.bin file in the [correct place?](https://github.com/FUComplete/Patch#where-do-i-place-configbin) (in the handheld or emulator)

**Comment by imeasyplease** [comment]
Yes that was the solution, thank you.
