### ISSUE TITLE
I kinda made it work on linux, how about a linux version?

### ISSUE THREAD

**Issue by denisstrizhkin** [FUComplete/FUCTool#7]
![image](https://github.com/FUComplete/FUCTool/assets/57726946/7471b12e-f9bb-476e-8409-70522b0cdb3e)

https://github.com/Snakes128/UMD-replace_x64

UMD-replace is compilelable on linux and xdelta3 is already pretty popular package available in all distros

What I think is required:
- Have an if condition that will use non exe `xdelta3` and `UMD-replace` on linux
- requirements.txt or possible even a project install rules like pyproject.toml or something

Also I think it would be nice if https://github.com/IncognitoMan/mhff had a setup.py file. I made it work by coping one from mhef so it shouldn't be that hard.

**Comment by denisstrizhkin** [comment]
Or maybe put a foss license on this repos if it is possible of course, so I can fork it.

**Comment by Hairo** [comment]
Yes, all 3 external binaries (xdelta, umd-replace and SEC-PC) should be buildable on linux, but the current windows build was tested and works perfectly with wine (in fact, the windows builds were made in linux with a 32bit wine prefix to ensure windows 7 compatibility). So we didn't feel the need to make a separate build for linux.

Feel free to fork or make a PR though, just added a license, an appimage would probably be the best choice.

**Comment by denisstrizhkin** [comment]
Thanks, I created the PR
